### ISSUE TITLE
Renaming class: avoid replace existing file warning if only case is changed (on Windows).

### ISSUE THREAD

**Issue by gene-pavlovsky** [fdorg/flashdevelop#1288] opened 2016-07-21 13:33 UTC
Got a project with interface files called `iSomeInterface`. Renaming it to `ISomeInterface` and getting a confirm dialog that file already exists (since on Windows file system is case-insensitive), "Would you like to replace?". Basically, on Windows, this dialog should only appear if `oldName.toLowerCase() != newName.toLowerCase`. Considering FD would (hopefully) be available for Linux one day, this should only apply on a case-insensitive filesystem.

**Comment by Neverbirth** [comment] 2016-07-21 13:39
"Nice" to see this bug back...

**Comment by gene-pavlovsky** [comment] 2016-07-22 06:08
Another part of this bug is if the iSomething is open in a tab, then it's renamed in the project panel, the tab title doesn't update. So the file is already ISomething, but tab is titled iSomething.

**Comment by wise0704** [comment] 2016-07-23 16:13
Possible duplicate of #1278

**Comment by gene-pavlovsky** [comment] 2018-07-10 12:42
It seems that the first part of the issue is fixed. It's possible to do a rename which only changes the case.
However, the tab title is not updated in this case. It is updated correctly if the rename involves more than a case change.

**Closed** 2018-07-26 10:08 UTC
Labels: bug, coderefactor
