### ISSUE TITLE
Reproducible: tab loses indent wrongly and autocomplete thinks I'm outside a function

### ISSUE THREAD

**Issue by GimmickyApps** [fdorg/flashdevelop#1132] opened 2016-03-17 11:52 UTC
HD 5.1.1.1 and FD 5.1.0.3 on Win7x64 both exhibit this problem, but *only* lately and only in one particular file of my project:

![tabswrong](https://cloud.githubusercontent.com/assets/16719964/13845125/20f0a6c2-ec3e-11e5-852b-06c892257901.gif)

Now, I've had this happen before in other contexts, but it always came down to a missing bracket somewhere in the file, and therefore not in valid code.

But in *this* context, the project actually compiles and runs without trouble.  This problem persists between restarts of HD / FD.  (BTW is this where to report HaxeDevelop bugs?  Or is there a separate issue tracker somewhere?  I couldn't find it.  In any case this also applies to FlashDevelop, I've verified.)

Here is a reproducible example file:

```haxe
package;

class ABC
{
	function a(?b:Void->Void) 
	{
	}
	function c() 
	{
		var myVar:String;
		if (true) {
		}
	}
}
```

Put the cursor after the `if (true) {` and hit enter, then type `my`.  You don't get `myVar` and you lose a tab indent.  If you take away the `?b:Void->Void` it works fine.  If you comment out all of function `a()` it also works fine.

**Comment by Neverbirth** [comment] 2016-03-17 16:32
Duplicate of #1125

**Closed** 2016-03-17 16:32 UTC

**Comment by GimmickyApps** [comment] 2016-03-17 17:51
Thanks, sorry for the dupe.  I did search, just used different terms than in the other issue.  :)

**Comment by Neverbirth** [comment] 2016-03-17 17:52
No problem at all. Will try to fix it during this week.

**Comment by GimmickyApps** [comment] 2016-03-17 17:54
Sweet!
