### ISSUE TITLE
Refactor rename behavior

### ISSUE THREAD

**Issue by kamcknig** [fdorg/flashdevelop#888] opened 2015-09-30 19:20 UTC
Per forum topic at http://www.flashdevelop.org/community/viewtopic.php?f=5&t=12352&p=54471#p54471

After using the rename refactor option, the caret ends up at the last item renamed. Could it move back to the original source of the rename?

Also, not sure how keen support for flex development is, but currently the rename reafctor does not rename anything within mxml if you rename a variable within the CDATA script

**Comment by SlavaRa** [comment] 2016-04-26 09:45
@kamcknig Hi, have you tried version 5.1.1? If the issue is not relevant, please close it.

**Comment by kyle-mcknight** [comment] 2016-04-26 13:17
@SlavaRa I have version 5.1.1.1 and it still does it. I have a file with 793 lines, put the cursor on a variable at line 79 and rename and the view moves so that the last use of the variable is at the bottom of the view.

**Comment by SlavaRa** [comment] 2016-04-26 13:47
I thought this was fixed in release.
It is does not work in 5.5.1, but working in develop version.

**Closed** 2018-07-18 11:11 UTC
Labels: coderefactor
