### ISSUE TITLE
[AS3] F4 does not always show definition of functions

### ISSUE THREAD

**Issue by neuronix** [fdorg/flashdevelop#1976] opened 2018-01-24 14:14 UTC
Observed behavior
1. Place cursor on function
2. Press F4
3. Not redirected to function definition

This seems to be related to all methods of certain classes even if F4 works on class definition, does not work on class methods.

**Comment by SlavaRa** [comment] 2018-01-24 14:18
Maybe you will give some minimum code?
what version of the editor do you use?

**Comment by neuronix** [comment] 2018-01-24 14:20
Hi Slava, sorry for the lacking version, using 5.3.1. Will try and come up with a minimum test case & send gist.

**Comment by SlavaRa** [comment] 2018-01-24 14:20
Thanks @neuronix :)

**Comment by SlavaRa** [comment] 2018-01-25 16:14
@neuronix Any news?

**Comment by neuronix** [comment] 2018-01-25 16:16
@SlavaRa sorry, not yet, i'm a too busy just now. I have been looking for similarities but some classes work at some times then not later etc. 

I did notice that in some cases, selecting the class name (double click to select the text) works whereas single clicking and leaving the | in the name does not.

Will get back to you asap!

**Comment by matrix3d** [comment] 2018-02-05 02:54
@SlavaRa yes,the f4 not work,sometimes.

**Comment by SlavaRa** [comment] 2018-02-05 08:13
How to reproduce it?

**Comment by matrix3d** [comment] 2018-02-11 05:21
`package  
{
	/**
	 * ...
	 * @author lizhi
	 */
	public class SkinAnimationCtrl
	{
		public var anim:Object;
		public var anims:Array = [];
		private var startTime:Number = 0;
		public var time:Number = 0;
		public var animtime:Number = 0;
		public var playing:Boolean = true;
		public var transitionAnim:Object;
		public function SkinAnimationCtrl() 
		{
			
		}
		
		override public function update(time:int,node:Object):void 
		{
			if (anim) {
				if(playing){
					this.time = time;
				}
				if (startTime==-1){
					startTime = this.time;
				}
				
				var t:Number = (this.time-startTime) / 1000;
				while (playing&&t > anim.maxTime){
					if (anim.timeline.update(t / anim.maxTime)){//如果脚本中断操作，则退出
						this.time = startTime+anim.maxTime * 1000 * anim.timeline.exitTime;
						anim.update(anim.timeline.exitTime*anim.maxTime,node);
						return;
					}
					anim.timeline.nextloop();
					//超过一圈
					startTime += anim.maxTime * 1000;
					t -= anim.maxTime;
					if (anim.maxTime<=0){
						break;
					}
				}
				if (anim.timeline.update(t / anim.maxTime)){
					this.time = startTime+anim.maxTime * 1000 * anim.timeline.exitTime;
					anim.update(anim.timeline.exitTime*anim.maxTime, node);
				}else{
					anim.update(t, node);
				}
			}
		}
		
		public function play(name:String,transitionTime:int):Object{
			startTime =-1;
			var fanim:SkinAnimation;
			for each(var a:SkinAnimation in anims){
				if (a.name==name){
					fanim = a;
					break;
				}
			}
			playing = true;
			
			if (fanim){
				if (transitionTime>0&&anim){
					if (transitionAnim==null){
						transitionAnim = new SkinAnimation;
						transitionAnim.name="__transition"
					}
					for each(var t:Track in tracks){
						var t2:Track = new Track;
						t2.targetName = t.targetName;
						for each(var f:TrackFrame in t.frames){
							var f2:TrackFrame = new TrackFrame;
							f2.time = f.time;
							f2.matrix = f.matrix.clone();
							t2.frames.push(f2);
						}
						c.tracks.push(t2);
					}
					c.bindShapeMatrix = bindShapeMatrix;
					c.maxTime = maxTime;
				}else{
					anim = fanim;
				}
			}
			
			return fanim;
		}
		
		public function stop():void{
			playing = false;
		}
		
		public function add(anim:SkinAnimation):void {
			this.anim = anim;
			anims.push(anim);
			play(null,0);
		}
		
		override public function clone():Ctrl 
		{
			var c:SkinAnimationCtrl = new SkinAnimationCtrl;
			c.add(anim.clone());
			return c;
		}
	}

}`

**Comment by SlavaRa** [comment] 2018-02-15 11:44
```actionscript
package {
	public class Issue1976 {
		public function add():void {
		}
		
		public function clone():Object {
			var c:Issue1976;
			c.ad|d();
			return c;
		}
	}
}
```
`|` - cursor

**Comment by SlavaRa** [comment] 2018-02-15 11:50
Will be fixed today, I'm sorry

**Comment by SlavaRa** [comment] 2018-02-15 14:11
Please try build from #2032

**Comment by matrix3d** [comment] 2018-02-26 03:36
the 5.3.3.1 also not work

**Comment by matrix3d** [comment] 2018-02-26 03:39
this line 
https://github.com/matrix3d/recast4j/blob/master/src/test/RecastSoloMeshTest.as#L111

.load()

**Comment by matrix3d** [comment] 2018-02-28 02:29
@SlavaRa maybe this bug need re open.

**Comment by SlavaRa** [comment] 2018-02-28 05:31
@matrix3d Hi, I should check it

**Comment by matrix3d** [comment] 2018-02-28 06:17
@SlavaRa thanks

**Comment by SlavaRa** [comment] 2018-02-28 11:20
@matrix3d please try latest development build, from http://flashdevelop.org/downloads/builds/

**Comment by matrix3d** [comment] 2018-03-01 06:23
![f4buggif](https://user-images.githubusercontent.com/4150631/36829872-06da5f70-1d5c-11e8-9b91-78b6b9da6646.gif)
https://github.com/fdorg/flashdevelop/commit/72662e0730

**Comment by matrix3d** [comment] 2018-03-01 06:49
@SlavaRa

**Comment by SlavaRa** [comment] 2018-03-01 07:01
It's magic :( Can you say me which version works good?
http://www.flashdevelop.org/community/viewforum.php?f=11

**Comment by matrix3d** [comment] 2018-03-01 07:13
5.3.0 work

**Comment by matrix3d** [comment] 2018-03-01 07:16
@SlavaRa Can you reproduce this bug? The code I provided should be easily reproduced. Now there's a lot of problems in this version of F4

**Comment by SlavaRa** [comment] 2018-03-01 07:18
No, I can't reproduce this bug :( 
Can you give me some project where bug reproduce?

**Comment by matrix3d** [comment] 2018-03-01 07:25
can you try this proj?
https://github.com/matrix3d/recast4j/blob/master/recast4j-as3.as3proj

this code

https://github.com/matrix3d/recast4j/blob/master/src/test/RecastSoloMeshTest.as#L111

**Comment by matrix3d** [comment] 2018-03-01 07:27
f4 the ObjImporter

**Comment by SlavaRa** [comment] 2018-03-01 07:29
>Can you give me some project where bug is reproduce?

I mean all project with code. not project file

**Comment by matrix3d** [comment] 2018-03-01 07:32
@SlavaRa this is the all project with code

https://github.com/matrix3d/recast4j

**Comment by SlavaRa** [comment] 2018-03-01 07:34
Thanks @matrix3d. I think that now I can find a bug in the course of the day.

**Comment by SlavaRa** [comment] 2018-03-02 07:12
@matrix3d please try development-build from https://ci.appveyor.com/project/FlashDevelop/flashdevelop-devel/build/5.3.3.13-lynciepp/artifacts

**Comment by matrix3d** [comment] 2018-03-02 07:19
@SlavaRa this version is ok.thanks

**Comment by matrix3d** [comment] 2018-03-02 07:23
This version is OK, but there is a small mistake, and occasionally press F4 2 times to jump.

**Comment by DarthVan** [comment] 2018-03-02 07:38
Hi! Have same problem before, but in 5.3.3.13 it works fine :)

> but there is a small mistake, and occasionally press F4 2 times to jump.

Oh ya, some times needs to press F4 twise.

**Comment by neuronix** [comment] 2018-03-09 14:11
F4 still does not work properly in some cases in latest dev build. (5.3.3.25)

**Comment by neuronix** [comment] 2018-03-12 14:42
I have a feeling this is related to not detecting the correct class when the package is missing. If I F4 on MyClass in a file it doesn't work, but go up to the imports, F4 on my.package.MyClass and it works.

**Comment by SlavaRa** [comment] 2018-03-22 14:00
@neuronix Can you give me code for test?

**Comment by neuronix** [comment] 2018-03-23 08:05
Hi @SlavaRa here is the simplest sample I found: 

test.Test
test2.Test2 extends test.Test
test2.Test3 extends test2.Test2

In Main, var t:Test3 = new Test3();

- in Main, F4 on Test3 in extends line => go to Test2
- in Test2, F4 on Test in extends line => nothing happens

FD 5.3.3.24 dev build #41209c0c3f

[src.zip](https://github.com/fdorg/flashdevelop/files/1840622/src.zip)

**Comment by SlavaRa** [comment] 2018-03-23 12:00
@neuronix Thanks

**Comment by SlavaRa** [comment] 2018-03-23 13:25
@neuronix fixed #2090

**Closed** 2018-03-23 16:51 UTC
Labels: bug

**Comment by neuronix** [comment] 2018-03-29 10:30
@SlavaRa Thanks man! :)

**Comment by neuronix** [comment] 2018-04-09 08:25
@SlavaRa this is not totally fixed yet, there are still some occasions when F4 does not work. However, F4 on the import in the same file always works.

**Comment by neuronix** [comment] 2018-04-09 08:40
I also noticed that sometimes F4 on a class definition will take me somewhere else... like F4 on MyClass and FD opens up SomeLib.as. And it's random ! Starting again, works fine.
