### ISSUE TITLE
Parenthesis in autocompletion

### ISSUE THREAD

**Issue by markknol** [fdorg/flashdevelop#1076] opened 2016-02-12 10:40 UTC
On a String in a Haxe project, I see this:
![image](https://cloud.githubusercontent.com/assets/576184/13004678/1f43b16a-d17d-11e5-9651-69f78ab75395.png)

I checked the source of String in Haxe, it does not contain extra parenthesis, so it's not me.

I use latest git version
![image](https://cloud.githubusercontent.com/assets/576184/13004700/43e0064a-d17d-11e5-8fb6-f0b286a2d9e0.png)

**Comment by Neverbirth** [comment] 2016-02-12 10:43
Duplicate of #1075

**Closed** 2016-02-12 10:42 UTC
